#based on https://cloud.google.com/appengine/docs/standard/python3/config/appref 
# this is helpful too https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/appengine/standard_python3/hello_world 

runtime: python38 

instance_class: F2

handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto